# jenkins

---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: linebot
  labels:
    name: linebot
spec:
  serviceName: linebot
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      name: linebot
      labels:
        name: linebot
    spec:
      terminationGracePeriodSeconds: 10
      volumes:
      - name: linebot-secrets
        secret:
          secretName: linebot
          items:
          - key: key.js
            path: key.js
      containers:
        - name: linebot
          image: peterlee0127/linebot
          imagePullPolicy: Always
          volumeMounts:
          - name: linebot-secrets
            mountPath: /var/secrets/
          ports:
            - containerPort: 8081
          resources:
            limits:
              cpu: 0.5
              memory: 200Mi
            requests:
              cpu: 0.3
              memory: 100Mi
          livenessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 10
            timeoutSeconds: 5
            failureThreshold: 12 # ~2 minutes
          readinessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 10
            timeoutSeconds: 5
            failureThreshold: 12 # ~2 minutes
      securityContext:
        fsGroup: 1000

---
apiVersion: v1
kind: Service
metadata:
  name: linebot
spec:
  selector:
    name: linebot
  #type: LoadBalancer
  #type: NodePort
  type: ClusterIP
  #externalTrafficPolicy: Local
  ports:
    -
      name: http
      port: 80
      targetPort: 8081
      protocol: TCP

---
